"""
===============================================================================
Project      : TGBackup
File         : test_workflow.py
Description  : Comprehensive end-to-end integration test suite: Full, Incremental,
               Cloud Scrub, Disaster Recovery (reindex), and bit-by-bit integrity.
Purpose      : Validates the entire lifecycle of all core TGBackup features:
               1. Full backup with filesystem snapshot & concurrent multi-bot upload.
               2. Zero-byte incremental backup (no changes detected).
               3. Incremental backup with modified and new files (deduplication).
               4. Cloud Scrub: verify existence of remote chunks on Telegram.
               5. Multi-layer incremental restore with overlay verification.
               6. Disaster Recovery: complete deletion of local vault.db and full
                  reconstruction from Telegram via encrypted master catalog.
===============================================================================
"""

import os
import sys
import shutil
import tempfile
import asyncio
from tgbackup.config import save_config
from tgbackup.cli import do_backup, do_list, do_restore, do_check, do_reindex
from tgbackup.db import VaultDB


class Args:
    """
    Simulates the Namespace object generated by argparse.
    """
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)


async def run_full_suite():
    """
    ---------------------------------------------------------------------------
    Function: run_full_suite
    Description:
        Executes the 7-step integration test suite verifying backup, restore,
        cloud integrity checks, and disaster recovery reindexing.
    Input parameters:
        None
    Return value:
        None
    Exceptions raised:
        AssertionError: If any verification condition fails.
    ---------------------------------------------------------------------------
    """
    with tempfile.TemporaryDirectory(prefix="tgb_test_suite_") as work_dir:
        src_dir = os.path.join(work_dir, "test_source")
        os.makedirs(os.path.join(src_dir, "subdir"), exist_ok=True)
        
        # 1. Create initial sample files
        f1_path = os.path.join(src_dir, "file1.txt")
        with open(f1_path, "w") as f:
            f.write("Version 1.0 of the text file\n" * 200)
            
        f2_path = os.path.join(src_dir, "subdir", "binary.dat")
        with open(f2_path, "wb") as f:
            f.write(os.urandom(128 * 1024))  # 128 KB

        cfg_path = os.path.join(work_dir, "test_config.json")
        db_path = os.path.join(work_dir, "test_vault.db")
        
        # Override DB path to isolate the test
        import tgbackup.db
        import tgbackup.cli
        tgbackup.db.DEFAULT_DB_PATH = db_path
        tgbackup.cli.DEFAULT_DB_PATH = db_path

        staging_path = os.path.join(work_dir, "staging_area")
        local_mirror_path = os.path.join(work_dir, "local_hdd_backup")

        test_cfg = {
            "channel_id": "-1001234567890",
            "bot_tokens": ["123456:BOT_A", "123456:BOT_B", "123456:BOT_C"],
            "passphrase": "super_secret_suite_passphrase!",
            "use_topics": True,
            "notif_topic_name": "Notifications Test",
            "notif_topic_id": 999,
            "chunk_size_mb": 1,
            "compression_level": 3,
            "staging_dir": staging_path,
            "local_backup_dir": local_mirror_path,
            "rate_limit_per_minute": 60,
            "retention": {
                "keep_daily": 5,
                "keep_weekly": 2,
                "keep_monthly": 2
            },
            "profiles": {
                "docs": {
                    "paths": [src_dir],
                    "excludes": [".cache"],
                    "topic_name": "Docs_Topic",
                    "topic_id": 888
                }
            }
        }
        save_config(test_cfg, cfg_path)

        print("\n=== 1. INITIAL FULL BACKUP TEST (CONCURRENT MULTI-BOT) ===")
        backup_args = Args(config=cfg_path, profile="docs", all=False, full=True, mock=True)
        await do_backup(backup_args)

        async with VaultDB(db_path) as db:
            snaps = await db.get_snapshots("docs")
            assert len(snaps) == 1, "Expected 1 initial snapshot"
            snap1_id = snaps[0]["id"]
            parts1 = await db.get_snapshot_parts(snap1_id)
            print(f"Full snapshot created: {snap1_id} with {len(parts1)} parts.")

        # Verify local disk mirror sync
        mirror_docs = os.path.join(local_mirror_path, "docs")
        assert os.path.exists(mirror_docs), "Local mirror directory must exist"
        mirror_files = os.listdir(mirror_docs)
        assert len(mirror_files) > 0, "Local mirror must contain chunks and manifest"
        print(f"[OK] Local disk mirror verified with {len(mirror_files)} files in {mirror_docs}")

        await asyncio.sleep(1.1)
        print("\n=== 2. ZERO-BYTE INCREMENTAL BACKUP TEST (NO CHANGES) ===")
        incr_args1 = Args(config=cfg_path, profile="docs", all=False, full=False, mock=True)
        await do_backup(incr_args1)

        async with VaultDB(db_path) as db:
            snaps = await db.get_snapshots("docs")
            assert len(snaps) == 2, "Expected 2 snapshots"
            snap2 = snaps[0]
            assert snap2["total_parts"] == 0, "No new chunks expected for unchanged snapshot"
            print(f"Incremental snapshot verified: {snap2['id']} (0 parts uploaded, 100% savings)")

        print("\n=== 3. INCREMENTAL BACKUP TEST WITH MODIFIED & NEW FILES ===")
        # Modify an existing file and create a new file
        await asyncio.sleep(1.1)  # Guarantees distinct mtime
        with open(f1_path, "a") as f:
            f.write("ROW UPDATE: This is the modified version 2.0!\n")
        
        f3_path = os.path.join(src_dir, "file3_new.txt")
        with open(f3_path, "w") as f:
            f.write("New file added subsequently.\n")

        incr_args2 = Args(config=cfg_path, profile="docs", all=False, full=False, mock=True)
        await do_backup(incr_args2)

        async with VaultDB(db_path) as db:
            snaps = await db.get_snapshots("docs")
            assert len(snaps) == 3, "Expected 3 total snapshots"
            snap3_id = snaps[0]["id"]
            snap3_parts = await db.get_snapshot_parts(snap3_id)
            print(f"Incremental snapshot created: {snap3_id} with {len(snap3_parts)} new parts.")

        print("\n=== 4. TOMBSTONE PRUNING INCREMENTAL BACKUP TEST ===")
        # Delete file3_new.txt and take an incremental snapshot
        await asyncio.sleep(1.1)
        os.remove(f3_path)
        assert not os.path.exists(f3_path)

        incr_args3 = Args(config=cfg_path, profile="docs", all=False, full=False, mock=True)
        await do_backup(incr_args3)

        async with VaultDB(db_path) as db:
            snaps = await db.get_snapshots("docs")
            assert len(snaps) == 4, "Expected 4 total snapshots"
            snap4_id = snaps[0]["id"]
            print(f"Snapshot with deleted file created: {snap4_id}")

        print("\n=== 5. CATALOG LIST TEST ===")
        list_args = Args(config=cfg_path, profile="docs")
        await do_list(list_args)

        print("\n=== 6. CLOUD SCRUB TEST (VERIFY TELEGRAM REMOTE CHUNKS) ===")
        check_args = Args(config=cfg_path, mock=True)
        await do_check(check_args)

        print("\n=== 7. LAYERED INCREMENTAL RESTORE TEST WITH TOMBSTONE PRUNING ===")
        restore_dest = os.path.join(work_dir, "restored_final")
        restore_args = Args(config=cfg_path, snapshot_id=snap4_id, destination=restore_dest, mock=True)
        await do_restore(restore_args)

        # Verify bit-by-bit integrity of remaining files
        restored_f1 = os.path.join(restore_dest, "test_source", "file1.txt")
        restored_f2 = os.path.join(restore_dest, "test_source", "subdir", "binary.dat")
        restored_f3 = os.path.join(restore_dest, "test_source", "file3_new.txt")

        assert os.path.exists(restored_f1), "file1.txt must be restored"
        assert os.path.exists(restored_f2), "binary.dat must be restored"
        # file3_new.txt was deleted in snap4, so tombstone pruning MUST remove it from destination
        assert not os.path.exists(restored_f3), "file3_new.txt must be pruned by tombstone deletion"

        with open(f1_path, "r") as f_orig, open(restored_f1, "r") as f_rest:
            assert f_orig.read() == f_rest.read(), "file1.txt content matches byte-for-byte"
        with open(f2_path, "rb") as f_orig, open(restored_f2, "rb") as f_rest:
            assert f_orig.read() == f_rest.read(), "binary.dat content matches byte-for-byte"

        print("[OK] INCREMENTAL RESTORE & TOMBSTONE PRUNING PASSED: Files matched, deleted file pruned!")

        print("\n=== 8. DISASTER RECOVERY TEST (ZERO-ARG AUTO REINDEX) ===")
        # SIMULATE DISASTER: Total deletion of local SQLite database file!
        if os.path.exists(db_path):
            os.remove(db_path)
            print("[INFO] SIMULATED DISASTER: Local vault.db file deleted from disk!")

        # Run Reindex without specifying message_id (auto-detected from pinned message)
        reindex_args = Args(config=cfg_path, message_id=None, mock=True)
        await do_reindex(reindex_args)

        # Verify DB was completely rebuilt
        async with VaultDB(db_path) as db:
            rebuilt_snaps = await db.get_snapshots("docs")
            assert len(rebuilt_snaps) == 4, f"Expected 4 recovered snapshots, found {len(rebuilt_snaps)}"
            print(f"[OK] AUTO DISASTER RECOVERY SUCCEEDED: Rebuilt {len(rebuilt_snaps)} snapshots from pinned catalog!")

        print("\n=== 9. PROCESS LOCK COLLISION TEST ===")
        from tgbackup.lock import ProcessLock, ProcessLockedError
        test_lock_file = os.path.join(work_dir, "test_proc.lock")
        lock1 = ProcessLock(test_lock_file)
        lock2 = ProcessLock(test_lock_file)

        lock1.acquire()
        try:
            collision_detected = False
            try:
                lock2.acquire()
            except ProcessLockedError:
                collision_detected = True
            assert collision_detected, "Second lock acquisition must raise ProcessLockedError"
            print("[OK] Process lock concurrency collision correctly detected and prevented!")
        finally:
            lock1.release()

    print("\n[SUCCESS] ALL 9 INTEGRATION TESTS PASSED 100%!\n")


if __name__ == "__main__":
    asyncio.run(run_full_suite())
